# Generated by Django 4.0.5 on 2022-07-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_artifact_model3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='size',
            field=models.CharField(blank='True', max_length=50),
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='usage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('silver', 'Silver'), ('wood', 'Wood')], default='glass', max_length=50),
        ),
    ]
