# Generated by Django 4.0.5 on 2022-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_archivedocument_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='color',
            field=models.CharField(blank='True', max_length=50),
        ),
    ]
